### ISSUE TITLE
Logs are not working 

### ISSUE THREAD

**Issue by amkhullar** [nccgroup/BurpSuiteLoggerPlusPlus#72] opened 2019-07-04 04:39 UTC
In the Burpsuite version 2.1 - Prof edition if u clear the logs then new logs are not displayed, u have to restart the burp tool to get the logs displayed.

**Comment by CoreyD97** [comment] 2019-08-08 08:05
Apologies for not responding about this issue sooner. I've been quite busy recently.

This was caused by an underlying issue in the implementation of the JTable. I've rewritten the table model which should have fixed this issue. The fix is currently in the development branch but will be merged into master soon.

**Closed by CoreyD97** 2019-08-08 08:05 UTC
